### ISSUE TITLE
Add after-save exclusively for wounds

### ISSUE THREAD

**Issue by sedulam** [damonhook/aos-statshammer#60]
Looking at the picture, this means that a MW would have one or two after-saves?
![Screenshot_20200904-071848](https://user-images.githubusercontent.com/9039639/92206755-ed6fb600-ee7f-11ea-9eb0-883d6e133744.png)
Since GHB2020, we can only have one after-save, but if both target modifiers above are cumulative, then there's currently no way to configure Nagash's target modifiers to account for his Morikhane (MWs negate on 4+), and his Deathless Minions (wounds negate on 6+). Deathless Minions also negates MWs, but Morikhane é the obvious choice since it is a 4+ negate. 
This would be solved by an after-save exclusively for wounds, and not MWs.

**Comment by sedulam** [comment]
Hi @damonhook ! I saw the ticket #61 , but these are two different things. Currently we still only have the "Target Feel No Pain" and the "Target Mortal Wounds Negate". To simulate allocating wounds on Nagash, we would need a 3rd target modifier that would only negate normal wounds (not MWs). Because Nagash has its native Deathless Minions (ignore wounds and MWs on a 6+), and Morikhane (ignore MWs on a 4+), logically, Nagash will use Deathless Minions for normal wounds, and it'll use Morikhane for MWs. Is my understanding this correctly, or am I missing how this should be configured in the Target Modifiers?
Cheers, and thanks for all your work again!
![image](https://user-images.githubusercontent.com/9039639/93593479-1cbc1200-f9ac-11ea-8fa1-7c32135c3183.png)

**Comment by damonhook** [comment]
Hi, so the decision of which target modifier to use is handled by the backend API. The idea is that you put the modifiers down as they appear on the scroll and let the API figure out the best way to apply it

So here are some scenarios:

---
You have:

- FNP: 6+
- MW Negate: 5+

It will use the MW Negate for all mortal wounds, and the FNP for normal wounds

---
You have:

- FNP: 4+
- MW Negate: 6+

It will always use the FNP (since the roll is better)

---
You have:

- FNP: 6+
- FNP: 4+

It will use the 4+ FNP as the roll is better.

---
I hope that answers your question

**Comment by sedulam** [comment]
Perfect, thanks for the clarification! Can I suggest you add this information on the page for the target modifiers? I think it's very useful info to know. 👍 I'm sorry if this is already somewhere in the site and I missed it though.
